apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clair 
  name: clair
  namespace: clair-inspect
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: clair 
  template:
    metadata:
      labels:
        app: clair
    spec:
      containers:
        - image: gcr.io/clair-inspect/clair
          imagePullPolicy: Always
          name: clair 
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}