apiVersion: v1
kind: Service
metadata:
  labels:
    name: clair-db
  name: clair-db
  namespace: clair-inspect
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: clair-db

