apiVersion: v1
kind: Service
metadata:
  labels:
    name: clair
  name: clair
  namespace: clair-inspect
spec:
  type: NodePort
  ports:
    - port: 6060
      targetPort: 6060
      name: default
    - port: 6061
      targetPort: 6061
      name: health
  selector:
    app: clair

